version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO_WEB: 026090550003.dkr.ecr.us-east-1.amazonaws.com/web-tier
    ECR_REPO_BACKEND: 026090550003.dkr.ecr.us-east-1.amazonaws.com/app-tier

phases:
  install:
    commands:
      - echo Nothing to install...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_WEB
  build:
    commands:
      - echo Build and tag Docker images...
      - docker build -t $ECR_REPO_WEB:latest ./application-code/web-tier
      - docker build -t $ECR_REPO_BACKEND:latest ./application-code/app-tier
  post_build:
    commands:
      - echo Push Docker images...
      - docker push $ECR_REPO_WEB:latest
      - docker push $ECR_REPO_BACKEND:latest
      - echo Copying Kubernetes manifests...
      - mkdir -p output/k8s
      - cp k8s/*.yaml output/k8s/

artifacts:
  files:
    - output/k8s/*.yaml
