version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO_WEB: "026090550003.dkr.ecr.us-east-1.amazonaws.com/web-tier"
    ECR_REPO_APP: "026090550003.dkr.ecr.us-east-1.amazonaws.com/app-tier"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REPO_WEB
  build:
    commands:
      - echo Build and tag Docker images...
      - docker build -t web-tier ./application-code/web-tier
      - docker tag web-tier:latest $ECR_REPO_WEB:latest
      - docker build -t app-tier ./application-code/app-tier
      - docker tag app-tier:latest $ECR_REPO_APP:latest
  post_build:
    commands:
      - echo Push Docker images...
      - docker push $ECR_REPO_WEB:latest
      - docker push $ECR_REPO_APP:latest
      - echo Writing image definitions...
      - printf '[{"name":"web-tier","imageUri":"%s"}]' $ECR_REPO_WEB:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
