version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.27
  pre_build:
    commands:
      - aws eks update-kubeconfig --region us-east-1 --name my-cluster
  build:
    commands:
      - kubectl apply -f k8s/
