apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: multi-tier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <your-backend-image> # Replace with your Docker Hub or ECR image
        ports:
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: multi-tier-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
