apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: multi-tier-app
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      sendfile        on;

      server {
        listen 80;

        location / {
          proxy_pass http://frontend:3000;
        }

        location /api/ {
          proxy_pass http://backend:4000/;
        }

        location /health {
          default_type text/html;
          return 200 "<!DOCTYPE html><p>Nginx Health Check</p>\n";
        }
      }
    }
